name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Order Service
      run: |
        docker build -t $REGISTRY/$IMAGE_PREFIX/order-service:latest ./order-service
        docker push $REGISTRY/$IMAGE_PREFIX/order-service:latest
