name: CD - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${PASSWORD}" | docker login -u "${USERNAME}" --password-stdin

    - name: Build and Push Order Service
      run: |
        docker build -t ${USERNAME}/order-service:latest ./order-service
        docker push ${USERNAME}/order-service:latest
